<a href="https://colab.research.google.com/github/TKM-MCA-2020-DATA-SCIENCE-LAB/20MCA315-BRAHMADUTTAN_S/blob/master/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
ls = [1,4,3]
np.array(ls)

array([1, 4, 3])

In [2]:
ls2 = [[1,2,3],[1,2,3],[4,5,7]]
np.array(ls2)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 7]])

In [3]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [11]:
np.random.rand()

0.18609936574126462

In [12]:
np.random.rand(1)

array([0.89242576])

In [13]:
np.random.rand(1,2)

array([[0.90176936, 0.32582686]])

In [14]:
np.random.randn()

1.5556415347941461

In [15]:
np.random.randint(1,8)

3

In [16]:
np.random.randint(1,8,10)

array([2, 3, 2, 1, 6, 2, 2, 1, 4, 3])

Array Attributes and Methods

In [17]:
arr= np.arange(25)
randarr= np.random.randint(1,100,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
randarr

array([45, 34, 41, 20, 89])

In [19]:
randarr.min()

20

In [20]:
randarr.max()

89

In [21]:
randarr.argmax()

4

In [22]:
randarr.argmin()

3

In [23]:

randarr.shape

(5,)

In [24]:
randarr.dtype

dtype('int64')

In [25]:

randarr[1]

34

In [26]:
ls2 = [[1,2,3],[1,2,3],[4,5,7]]
ls2[1:3]

[[1, 2, 3], [4, 5, 7]]

In [27]:
ls2=np.array(ls2)


In [28]:
ls2

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 7]])

In [29]:
ls2[1:2]

array([[1, 2, 3]])

In [30]:
ls2[1:2]

array([[1, 2, 3]])

# **Selection**


In [31]:
y = ls2[:,0] = 1
ls2[y,:]

array([1, 2, 3])